# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\AppCommands\:
        resource: '../src/AppCommands'
        tags: ['console.command']
    
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Core\File\FileReader\FileReaderInterface:
        class: App\Infrastructure\File\FileReader

    App\Application\Services\File\FileService:
        arguments:
            - '@App\Core\File\FileReader\FileReaderInterface'
    
    App\Application\Services\File\FileRequestValidator\FileRequestValidator:

    App\Controller\File\FileController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            - '@App\Application\Services\File\FileService'
            - '@App\Application\Services\File\FileRequestValidator\FileRequestValidator'

    App\Controller\File\FourierTransformController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            - '@App\Application\Services\File\FileService'
            - '@App\Application\Services\File\FileRequestValidator\FileRequestValidator'
        
    App\Infrastructure\ExternalProcessMemoryCollector\ExternalProcessMemoryCollector:
        arguments: []
        tags:
            - { name: 'data_collector', id: 'external_process_memory', template: '@WebProfiler/Collector/memory.html.twig', priority: 250 }
